### ISSUE TITLE
Update for "Using Rust in CRAN packages"

### ISSUE THREAD

**Issue by eitsupi** [eitsupi/prqlr#148]
2023-07-12, CRAN added a new policy for R packages including Rust codes.
<https://cran.r-project.org/web/packages/using_rust.html>

> Packages wishing to use Rust code should either
>
> - include the code in the package, or
> - download a specific version from a secure and reliable site and check that the download is the expected code by some sort of checksum. The expected checksum needs to be embedded in the source package. 
>
> In either case, the authorship and copyright information for the Rust code must be included in the DESCRIPTION file. That includes any Rust sources included as dependencies (see the CRAN policy). 

> The package should declare
> SystemRequirements: Cargo (Rust's package manager), rustc

> The configure/configure.win script should check for the presence of commands cargo and rustc, and check their versions if required. This includes checking for system versions on the path and personal versions in ~/.cargo/bin (which are often not on the path). The Linux servers on the CRAN check farm use system versions, and Linux distributions are often slow to update these so version requirements need to be conservative. 

> cargo build -j N defaults to the number of ‘logical CPUs’. This usually exceeds the maximum allowed in the CRAN policy, so needs to be set explicitly to N=1 or 2. 

> Downloading should be avoided if at all possible. The package would become uninstallable if the Internet resources are temporarily or permanently unavailable, and CRAN packages are kept available for many years. CRAN does not regard github.com (which hosts the index of crates.io and many of the crates) as sufficiently reliable.

- [x] Adds `inst/AUTHORS` (#150, #154, #160)
- [x] Use `SystemRequirements: Cargo (Rust's package manager), rustc` (#153)
- [x] Adds configure scripts (#149)
- [x] Set `cargo build -j 2` if not `NOT_CRAN=true` (#151)
- [x] Vendoring Rust dependent crates (#152, #159)
- [x] `LICENSE.note` should includes build time dependencies. (#156)

**Comment by eitsupi** [comment]
From CRAN

> CRAN packages downloading Rust components at installation
>
> That is
>
>    gifski hellorust prqlr rshift tok ymd
>
> The CRAN policy on authorship/copyright is very clear:
>
> "(’All components’ includes any downloaded at installation or during use.) "
>
> Please explain how your package complies if you believe it does.
>
> Further, we ask that you use the 'cargo vendor' mechanism to avoid downloading during installation and limit the number of CPUs 'cargo build' can use during installation.  Both points are covered in https://cran.r-project.org/web/packages/using_rust.html .
>
> Please correct before 2023-08-19 to safely retain your package on CRAN: submissions are now shut until 2023-08-07.

**Comment by eitsupi** [comment]
Vendoring would not pass the CRAN check due to the 12 MB size, so I removed the `vendor.tar.xz` file and submitted 0.5.0 to CRAN.
This needs to be documented.
